baseURL = 'https://dbolson.github.io/'
languageCode = 'en-us'
title = 'Rubber Duck Dialogs'

paginate = '10'
theme = 'mainroad'

[Params]
  post_meta = ['date']

[Params.sidebar]
  home = 'right'
  widgets = ['search', 'recent', 'categories', 'taglist']

[Params.widgets]
  recent_num = 5
